[package]
name = "todosite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
libsql-client = "0.31.6"
leptos = { version = "0.4.1", features = ["ssr"] }
anyhow = "1.0.71"
